services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=dF9xNTuZ433gAfG
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - opensearch-net
  # sbert-embedder:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.sbert
  #   container_name: sbert-embedder
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - opensearch-net
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: https://localhost:9200
    networks:
      - opensearch-net

networks:
  opensearch-net: